# -*- coding: utf-8 -*-
"""Sentiment Analysis with BERT Neural Network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vz0-HDcYohkj0v7Az2D7YPumWffvIqM8
"""


from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import requests
from bs4 import BeautifulSoup
import re

tokenizer = AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

model = AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

tokens = tokenizer.encode('Very bad', return_tensors='pt')

result = model(tokens)

int(torch.argmax(result.logits))+1

r = requests.get('https://www.yelp.com/biz/social-brew-cafe-pyrmont')
soup = BeautifulSoup(r.text, 'html.parser')
regex = re.compile('.*comment.*')
results = soup.find_all('p', {'class':regex})
reviews = [result.text for result in results]


import numpy as np
import pandas as pd

df = pd.DataFrame(np.array(reviews), columns=['review'])


def sentiment_score(review):
  tokens = tokenizer.encode(review, return_tensors = 'pt')
  result = model(tokens)
  return int(torch.argmax(result.logits))+1


df['sentiment'] = df['review'].apply(lambda x: sentiment_score(x[:512]))

print(df)